language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
# 1
before_install:
  - chmod +x mvnw

branches:
  only:
    - master

# 2
cache:
  directories:
    - '$HOME/.m2/repository'

before_deploy:
  - zip -r fastfood-springboot2-webservice *
  - mkdir -p deploy
  - mv fastfood-springboot2-webservice.zip deploy/fastfood-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fastfood-spring-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fastfood-spring-build
    region: ap-northeast-2
    key: fastfood-springboot2-webservice.zip
    bundle_type: zip
    application: fastfood-springboot2-webservice
    deployment_group: fastfood-springboot-webservice-group
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - dico2760@gmail.com