language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
# 1
branches:
  only:
    - master
addons:
  apt:
    packages:
      - oracle-java8-installer
# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - chmod +x mvnw

# 3
script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - dico2760@gmail.com