language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/'

before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - dev.dico2760@naver.com